### ISSUE TITLE
FloatCanvas different zooming factor for x and y

### ISSUE THREAD

**Issue by josephernest** [wxWidgets/wxPython-Classic#10]
A small question about FloatCanvas: is there a way to have a **different zooming factor for x and y**  (i.e. without keeping aspect ratio)? Or should hack the existing FloatCanvas to allow this?

____

A related question : let's say we have a 1000 x 1000 pixels image on the canvas. If we zoom x50 in x, and 50x in y, will this need to :

* store a 50.000 x 50.000 pixels image in memory (i.e. 2.5 giga pixels, i.e. 7.5 GB of data in 24-bit RGB?)

or

* store only the current viewport in memory (which is < 2000 x 2000 px)

**Comment by josephernest** [comment]
Any idea @RobinD42 for having different zooming factors for x and y ?

I'm coding an audio editor, and it's important to be able to have a different zooming factor for x (time) and y (amplitude), see [this screenshot](https://screenshot.it.sftcdn.net/it/scrn/6000/6765/sound-forge-21.jpg) for example.

Thanks in advance if you have an idea :)

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
