### ISSUE TITLE
Build fails: Can't find or import wxWidgets/build/tools/build-wxwidgets.py, exiting.

### ISSUE THREAD

**Issue by cztomczak** [wxWidgets/wxPython-Classic#11]
I have followed the instructions in docs/BUILD.txt and the build fails. Here are the steps I did:

1. Clone github repository: git clone https://github.com/wxWidgets/wxPython.git
2. cd wxPython/
3. python build-wxpython.py --build_dir=../build-wxPython --install
4. Error: `Can't find or import /home/cz/github/wxWidgets/build/tools/build-wxwidgets.py, exiting.`

Googled and found this post about cloning wxWidgets WX_3_0_BRANCH:
https://groups.google.com/d/msg/wxpython-mac/xCtXEVRyv-E/OL5dvwaOAQAJ

I think this should be added to BUILD.txt.

During build there was an error about gstreamer package missing, I've installed these packages and it worked: `gstreamer1.0 libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev`.

OS: Ubuntu 14.04 64-bit

**UPDATE**:

It should probably also be added that build must be run using "sudo" otherwise it fails:
```
/usr/bin/install: cannot create regular file ‘/usr/local/lib/libwx_baseu-3.0.so’: Permission denied
make: *** [install_basedll] Error 1
Traceback (most recent call last):
  File "build-wxpython.py", line 480, in <module>
    wxcfgsrc = glob.glob(wxlocation + '/lib/wx/config/*')[0]
IndexError: list index out of range
```

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
