### ISSUE TITLE
Fails to install when running Python using pyenv

### ISSUE THREAD

**Issue by cztomczak** [wxWidgets/wxPython-Classic#12]
I am building by following the instructions in docs/BUILD.txt. I also added `--install` flag. When build finishes I can see in the console:
```
Copying wxPython.egg-info to /usr/local/lib/python2.7/dist-packages/wxPython-3.0.3.0-py2.7.egg-info
```

It installed to system Python library location. However I was running the build/install script using Python installed with pyenv, thus it should install to:
```/home/cz/.pyenv/versions/2.7.13/lib/python2.7/site-packages```

I need wxpython 2.8 in my system Python. I want to install wxpython 3.0 only in another Python installation that is running using pyenv.

pyenv is a simple Python version management:
https://github.com/pyenv/pyenv

OS: Ubuntu 14.04 64-bit

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
