### ISSUE TITLE
Broken installation: ImportError: libwx_gtk2u_adv-3.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by cztomczak** [wxWidgets/wxPython-Classic#13]
I have built wxpython by following the build instructions from docs/BUILD.txt. There were some issues that I reported in Issue #11. I was building/install using Python running with pyenv, but despite this wxpython was installed to a system Python library location. Reportred this as Issue #12. Now I've tried to run wxpython using system Python, as this is where it installed, but I'm getting this error:

```
cz@comp:~/github/wxWidgets/wxPython$ python ../../cefpython/examples/wxpython.py 
Traceback (most recent call last):
  File "../../cefpython/examples/wxpython.py", line 11, in <module>
    import wx
  File "/usr/local/lib/python2.7/dist-packages/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/usr/local/lib/python2.7/dist-packages/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libwx_gtk2u_adv-3.0.so.0: cannot open shared object file: No such file or directory
```

Previously I've had installed wxpython 2.8 using Ubuntu software center. Now after building wxpython 3.0 it is broken now. I have a side question: How do I uninstall 3.0 and get back 2.8 working?

OS: Ubuntu 14.04 64-bit
Python 2.7.6

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
