### ISSUE TITLE
Editra can't load from wxpython 3.0.2.0

### ISSUE THREAD

**Issue by sl1pkn07** [wxWidgets/wxPython-Classic#14]
hi

i want build wxpython with certain tag (wxPy-3.0.2.0), but this tag (idk if other tags have the same issue) have missing folders
this folders is:

wxPython/wxPython/wx/lib/agw
wxPython/wxPython/wx/lib/floatcanvas
wxPython/wxPython/wx/lib/pdfviewer
wxPython/wxPython/wx/lib/pubsub
wxPython/wxPython/wx/lib/tools/Editra
wxPython/wxPython/wx/lib/tools/XRCed

without this folder, i cant build due missing this components

why this is the master branch have this folders?

greetings

**Comment by RobinD42** [comment]
Probably missing due to historical flaming hoops. Back when we were using SVN those folders were coming from a different location in the repository, which is something that did not translate well to Git.  In addition, when the old wxPython tags were made the structure of the files in the repository was changed (wxPython became a subfolder of wxWidgets) which also goes against the nature of Git.

I see 2 options for you. First, you can fetch the code from the subversion repository at http://svn.wxwidgets.org/svn/wx/wxPython/tags/wxPy-3.0.2.0/. Then you'll need to run wxPython/bin/subrepos-make to fetch the missing folders.  Or the simpler alternative would be to just use the source tarball for 3.0.2.0 at https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2/download.

**Comment by sl1pkn07** [comment]
yep, i'm go to use source tarball,  build ok, but have a little problem with Editra. when launch:

```
└───╼  editra
/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/usr/bin/editra", line 3, in <module>
    from wx.tools.Editra.launcher import main
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/tools/Editra/launcher.py", line 12, in <module>
    execfile(launcher)
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/tools/Editra/Editra'
```
(yep, is build against GTK3)

greetings

**Comment by RobinD42** [comment]
It looks like somewhere along the way (probably when transitioning to git) the .../tools/Editra/Editra file lost the leading uppercase 'E' and was renamed to editra. If you change that back to an uppercase 'E' then that should fix it for you.

**Comment by sl1pkn07** [comment]
Hi, nope,. seems the 'setup.py' not build/install the editra executable, because (after edit the Editra/launcher.py)

```
└───╼  editra
/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/usr/bin/editra", line 3, in <module>
    from wx.tools.Editra.launcher import main
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/tools/Editra/launcher.py", line 12, in <module>
    execfile(launcher)
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/tools/Editra/editra'
```

```
└───╼  ls /usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/tools/Editra/
total 176
drwxr-xr-x  9 root root  4096 ago  7 18:24 .
drwxr-xr-x  4 root root  4096 ago  6 11:19 ..
-rw-r--r--  1 root root   842 ago  6 02:40 AUTHORS
-rw-r--r--  1 root root  6229 ago  6 02:40 CHANGELOG
-rw-r--r--  1 root root  2500 ago  6 02:40 COPYING
-rwxr-xr-x  1 root root  3025 ago  6 02:40 Editra.pyw
-rw-r--r--  1 root root   211 ago  6 02:40 FAQ
-rw-r--r--  1 root root  2360 ago  6 02:40 INSTALL
-rw-r--r--  1 root root   612 ago  6 02:40 MANIFEST.in
-rw-r--r--  1 root root  1886 ago  6 02:40 Makefile
-rw-r--r--  1 root root   229 ago  6 02:40 NEWS
-rw-r--r--  1 root root  1160 ago  6 02:40 README
-rw-r--r--  1 root root   469 ago  6 02:40 THANKS
-rw-r--r--  1 root root   731 ago  6 02:40 TODO
-rw-r--r--  1 root root   743 ago  6 02:40 __init__.py
-rw-r--r--  1 root root   392 ago  6 02:47 __init__.pyc
-rw-r--r--  1 root root   392 ago  6 02:47 __init__.pyo
drwxr-xr-x  2 root root  4096 ago  6 11:19 docs
-rw-r--r--  1 root root   491 ago  7 18:24 launcher.py
-rw-r--r--  1 root root   310 ago  6 02:47 launcher.pyc
-rw-r--r--  1 root root   310 ago  6 02:47 launcher.pyo
drwxr-xr-x 29 root root  4096 ago  6 02:48 locale
drwxr-xr-x  3 root root  4096 ago  6 11:19 pixmaps
drwxr-xr-x  2 root root  4096 ago  6 11:19 plugins
-rw-r--r--  1 root root 21717 ago  6 02:40 setup.py
-rw-r--r--  1 root root 19144 ago  6 02:47 setup.pyc
-rw-r--r--  1 root root 19013 ago  6 02:47 setup.pyo
drwxr-xr-x  7 root root  4096 ago  6 11:19 src
drwxr-xr-x  2 root root  4096 ago  6 11:19 styles
drwxr-xr-x  3 root root  4096 ago  6 02:48 tests
```

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
