### ISSUE TITLE
ContextHelp fails on macOS

### ISSUE THREAD

**Issue by marcelstoer** [wxWidgets/wxPython-Classic#17]
Clicking the '?' in the ContextHelp example leads to the spinning beach ball of death on macOS. The app has to be force-quit.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
