### ISSUE TITLE
undefined symbol: _ZTI12wxEvtHandler

### ISSUE THREAD

**Issue by ioanb7** [wxWidgets/wxPython-Classic#18]
**Operating system**: Yocto
**wxPython version**: 3.0.2.0
**Stock or custom build**: custom
**Python version**: 2.7

**Description of the problem**: I've installed wxwidgets and wxpython, but I am getting a weird error. Any ideas?

```python
root@imx6ul-var-dart:~# pip freeze
smart==1.5
wxPython==3.0.2.0
wxPython-common==3.0.2.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


root@imx6ul-var-dart:~# python
Python 2.7.12 (default, Sep  2 2017, 23:59:37) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: /usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core_.so: undefined symbol: _ZTI12wxEvtHandler
>>> exit()
```

**Comment by RobinD42** [comment]
What commands did you do to build and/or install wxPython?

Did you use the wxWidgets included with wxPython or build it separately?

Is it possible that there is another wxWidgets already on your system that wxPython is trying to dynamically link to?

What is the output of `ldd /usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core_.so`?

**Comment by jaredd** [comment]
I am also seeing a similar error.  Here's some info

$ uname -a
Linux linux-xdol 4.12.9-1-default #1 SMP PREEMPT Fri Aug 25 07:08:45 UTC 2017 (f2ab6ba) x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20170928"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20170928"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20170928"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
$ pwd
/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython

Build command
$ python -u build-wxpython.py --prefix=$VIRTUAL_ENV --build_dir=../buildgtk --gtk3 --install

python -u build-wxpython.py --prefix=$VIRTUAL_ENV --build_dir=../buildgtk --gtk3
old_options = set(['--build_dir=../buildgtk', '--prefix=/home/jaredd/pyvenvs/gnuradio3.7', '--gtk3'])
sys.argv = ['--prefix=/home/jaredd/pyvenvs/gnuradio3.7', '--build_dir=../buildgtk', '--gtk3']
wxWidgets directory is: /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0
wxWidgets build options: ['--wxpython', '--jobs=4', '--prefix=/home/jaredd/pyvenvs/gnuradio3.7', '--gtk3', '--unicode', '--no_config', '--builddir=/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk']
Configure options: ['--enable-unicode', '--with-gtk=3', '--prefix=/home/jaredd/pyvenvs/gnuradio3.7', '--with-opengl', '--enable-sound', '--enable-graphics_ctx', '--disable-mediactrl', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--with-sdl']
/usr/bin/make
make --jobs=4
...
------------ BUILD FINISHED ------------

To run the wxPython demo you may need to:
 - set your PYTHONPATH variable to /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython

$ PYTHONPATH=/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython:$PYTHONPATH python -u demo/demo.py
Traceback (most recent call last):
  File "demo/demo.py", line 3, in <module>
    import Main
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/demo/Main.py", line 59, in <module>
    import wx              
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/_core.py", line 4, in <module>
    import _core_
ImportError: /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/_core_.so: symbol _ZN30_WX_LIST_HELPER_wxMenuItemList14DeleteFunctionEP10wxMenuItem, version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference


$ c++filt <<< _ZN30_WX_LIST_HELPER_wxMenuItemList14DeleteFunctionEP10wxMenuItem
_WX_LIST_HELPER_wxMenuItemList::DeleteFunction(wxMenuItem*)

$ ldd wx/_core_.so
ldd /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/_core_.so
	linux-vdso.so.1 (0x00007ffc08bba000)
	libwx_gtk3u_xrc-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_xrc-3.0.so.0 (0x00007f2b04371000)
	libwx_gtk3u_webview-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_webview-3.0.so.0 (0x00007f2b0414f000)
	libwx_gtk3u_html-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_html-3.0.so.0 (0x00007f2b03e7e000)
	libwx_gtk3u_qa-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_qa-3.0.so.0 (0x00007f2b03c4e000)
	libwx_gtk3u_adv-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_adv-3.0.so.0 (0x00007f2b0387e000)
	libwx_gtk3u_core-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_gtk3u_core-3.0.so.0 (0x00007f2b0305d000)
	libwx_baseu_xml-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_baseu_xml-3.0.so.0 (0x00007f2b02e4d000)
	libwx_baseu_net-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_baseu_net-3.0.so.0 (0x00007f2b02c08000)
	libwx_baseu-3.0.so.0 => /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib/libwx_baseu-3.0.so.0 (0x00007f2b0277a000)
	libpython2.7.so.1.0 => /usr/lib64/libpython2.7.so.1.0 (0x00007f2b02332000)
...

It seems like everything is in place, except some symbol is missing in the libraries.  Don't know if there are other missing syms.

**Comment by jaredd** [comment]
Follow up investigation, looking for the missing function in the code.

$ grep -R DeleteFunction include/
include/wx/list.h:154:        static void DeleteFunction( _WX_LIST_ITEM_TYPE_##liT X );             \
include/wx/list.h:296:                _WX_LIST_HELPER_##liT::DeleteFunction( i->GetData() );        \
include/wx/list.h:316:                               _WX_LIST_HELPER_##liT::DeleteFunction );       \
include/wx/listimpl.cpp:15:    void _WX_LIST_HELPER_##name::DeleteFunction( _WX_LIST_ITEM_TYPE_##name X )\

$ cat -n include/wx/list.h | head -n 160  | tail -n 15
   146	// the real wxList-class declaration
   147	#define WX_DECLARE_LIST_XO(elT, liT, decl)                                    \
   148	    decl _WX_LIST_HELPER_##liT                                                \
   149	    {                                                                         \
   150	        typedef elT _WX_LIST_ITEM_TYPE_##liT;                                 \
   151	        typedef std::list<elT> BaseListType;                                  \
   152	    public:                                                                   \
   153	        static BaseListType EmptyList;                                        \
   154	        static void DeleteFunction( _WX_LIST_ITEM_TYPE_##liT X );             \
   155	    };                                                                        \
   156	                                                                              \
   157	    WX_LIST_VC6_WORKAROUND(elT, liT, decl)                                    \
   158	    class liT : public std::list<elT>                                          \
   159	    {                                                                         \
   160	    private:                                                                  \

$ grep -nR WX_DECLARE_LIST_XO include/
include/wx/list.h:66:    WX_DECLARE_LIST_XO(elT*, liT, decl)
include/wx/list.h:147:#define WX_DECLARE_LIST_XO(elT, liT, decl)                                    \
include/wx/list.h:1291:WX_DECLARE_LIST_XO(wxString, wxStringListBase, class WXDLLIMPEXP_BASE);

It appears that there is no declaration of a list for wxMenuItem.  I must be missing something.

**Comment by jaredd** [comment]
The plot thickens.  It occurred to me that this giant code base may not be so straightforward.  So I found something that looked like a declaration of the wxMenuItemList::DeleteFunction.  It was within some #if  block that depended on wxUSE_STL or similar define.  So I added --enable-stl.  Rebuild and execute

$ PYTHONPATH=/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython:$PYTHONPATH LD_LIBRARY_PATH=/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/buildgtk/lib:$LD_LIBRARY_PATH python -u demo/demo.py

and a window comes up, but none of the demo selections bring up any kind of window, instead my console is filled with messages like

(demo.py:28461): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x2b97050 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(demo.py:28461): Gtk-WARNING **: Allocating size to GtkButton 0x2d7c180 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

So I try to install to my virtual env and run the demo again as instructed

$ PYTHONPATH=/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython:$PYTHONPATH python -u demo/demo.py
Traceback (most recent call last):
  File "demo/demo.py", line 3, in <module>
    import Main
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/demo/Main.py", line 59, in <module>
    import wx              
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/_core.py", line 4, in <module>
    import _core_
ImportError: /home/jaredd/pyvenvs/gnuradio3.7/src/wxPython-src-3.0.2.0/wxPython/wx/_core_.so: symbol _ZN30_WX_LIST_HELPER_wxMenuItemList14DeleteFunctionEP10wxMenuItem, version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference

Back to square one.

**Comment by jaredd** [comment]
Just to close this out on my end.  I never figured out what was wrong with gtk3.  I recompiled with gtk2 and was able to get the demo up and running without error.  Go figure.

**Comment by ioanb7** [comment]
I've followed this topic and expected some of the original developers to answer.

So I understand you were able to compile wxpython with gtk2 instead of gtk3 - by switching it in a dependency file? From what I know there are quite big differences between them so I wonder how that worked.

**Comment by ioanb7** [comment]
I wish I could've provided more detail but I didn't have ldd installed and on my embedded machine I didn't have any package manager to install it either.

**Comment by jaredd** [comment]
The default build option is gtk2.  If you look at my previous posts I give the build command line I used which explicitly requests gtk3.  I simply left this out.

$ python -u build-wxpython.py --prefix=$VIRTUAL_ENV --build_dir=../buildgtk --gtk3 --install

I remember making a short script that behaved like ldd but used objdump and scanned files from the LD_LIBRARY_PATH.  Not saying that it was simple, but you can synthesize the behavior.  Anyways, the original issue remains with gtk3, some symbols seemed to be missing in some of the libraries.  All the right libs appeared to be found according to ldd [here](https://github.com/wxWidgets/wxPython/issues/18#issuecomment-333739887).

**Comment by OzancanKaratas** [comment]
Phoenix project is already being used. I think we should delete this project from GitHub.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
