### ISSUE TITLE
build-wxpython.py breaks in windows

### ISSUE THREAD

**Issue by Lobotomik** [wxWidgets/wxPython-Classic#19]
The build-wxpython.py breaks here:

`if options.install:`
`    # only add the --prefix flag if we have an explicit request to do`
`    # so, otherwise let distutils install in the default location.`
`    install_dir = DESTDIR or PREFIX`

Because DESTDIR and PREFIX are only set in these lines

`DESTDIR = options.installdir`
`PREFIX = options.prefix`

which are only executed if sys.platform.startswith("win") is false.

**Comment by Lobotomik** [comment]
I have managed to produce a seemingly working build in 64-bit Windows10.
This entailed the following changes:

In build-wxpython.py

- Set the right CPU environment var for windows according to sysconfig.get_platform()
- Initialize DSTDIR and PREFIX to "" to prevent the issue discussed above
- Also for Windows, after the wxWidgets dll files are copied to WXPYDIR/wx, copy them also to setuptools build directory, so that they are installed too. Before this, the install in site-packages/... had no wxWidgets dlls and did not work.

In makefile.vc
- Set a new variable WINXX to WIN64 or WIN32 depending on the value for TARGET_CPU which is the same as the value in CPU. I don't know what would should the value be for IA64 (nor do I think anybody cares anymore).
- Change all occurrences of /DWIN32 to /D$(WINXX)
Without this, wxWidgets would compile to WIN32 regardless of the architecture and would not link against the 64-bit wxPython build.

With all this, "python build-wxpython.py --install" produces a working installation in my Lib/site-packages directory. 

I have also prepared the recipe files for a working anaconda tar.bz2 installable package.

I'd be happy to provide these changes for your evaluation. Please comment.

Oh, and to prevent more hair tearing, I think the help output should be updated to reflect that --installdir, --builddir, --build-dir and --wxpy_installdir are ignored for Windows builds.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
