### ISSUE TITLE
url loading issue of webview

### ISSUE THREAD

**Issue by carryinfo** [wxWidgets/wxPython-Classic#21]
hi, I am using webview, but come accross some problem, 

for the href which should jump to another window.   the wxpython webview has no reponse.

for the android viewview, user can override the webview method below, and return false:
public boolean shouldOverrideUrlLoading (WebView view, String url)

But in wxpython, how can I handle it?

in the bellow code, after the webview is loaded, I can't click any href in the view

```
import AppKit
from wx import wx

import wx.html2 as webview


AppKit.NSBundle.mainBundle().infoDictionary()['NSAppTransportSecurity'] = dict(NSAllowsArbitraryLoads = True)

ex = wx.App()
win = wx.Frame(None, wx.ID_ANY, "Hello World")
wv = webview.WebView.New(win)
wv.LoadURL("http://www.jianshu.com/")
win.Show(True)
ex.MainLoop()
```

**Comment by carryinfo** [comment]
any body help me?

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
