### ISSUE TITLE
MacLargeDemo  how to change percent through threading

### ISSUE THREAD

**Issue by SwpuEsine** [wxWidgets/wxPython-Classic#22]

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
