### ISSUE TITLE
bug on button evt_left_up

### ISSUE THREAD

**Issue by faststare** [wxWidgets/wxPython-Classic#25]
I just a bug on button evt_left_up, when button is focus and I will try to close the frame. button event still firing. when I use evt_button it seems fine. please fix this. thanks in advance.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
