### ISSUE TITLE
wx.ProgressDialog SetRange Problem

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/wxPython-Classic#26]
I create a ProgressDialog:
        dlg = wx.ProgressDialog("Progress dialog example",
                               "An informative message",
                               maximum = 100,
                               parent=self,
                               style = 0
                                | wx.PD_APP_MODAL
                                | wx.PD_CAN_ABORT
                                #| wx.PD_CAN_SKIP
                                #| wx.PD_ELAPSED_TIME
                                | wx.PD_ESTIMATED_TIME
                                | wx.PD_REMAINING_TIME
                                #| wx.PD_AUTO_HIDE
                                )
When I call dlg.SetRange method,It occur problem below:
Traceback (most recent call last):
  File "D:\env\wxpython_test\thread_test_2.py", line 137, in onButton2
    dlg.SetRange(120)
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_windows.py", line 3744, in SetRange
    return _windows_.GenericProgressDialog_SetRange(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "m_gauge" failed at ..\..\src\generic\progdlgg.cpp(610) in wxGenericProgressDialog::SetRange(): dialog should
 be fully created

But the dlg.Update and other method work nomal.
What's the probelm may be and How to avoid this ?

**Comment by wekay102200** [comment]
I discover this probem only occur on windows os system,It work ok on linux os system.

**Comment by wekay102200** [comment]
the dlg.Update and other method work fine,Only dlg.SetRange occur probem above.

**Comment by mesalu** [comment]
This ended up getting addressed in Phoenix, right?

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
