### ISSUE TITLE
%gui wx in Jupyter notebook crashes kernel

### ISSUE THREAD

**Issue by ghost** [wxWidgets/wxPython-Classic#28]
Hi, I was running my jupyter notebook under python2.7 environment, and the kernel crashes every time I run %gui wx on my first cell...
I have to use python2.7 to use mayavi, does anyone have any clue to solve this problem?

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
