### ISSUE TITLE
error in message

### ISSUE THREAD

**Issue by ousia** [wxWidgets/wxPython-Classic#29]
https://wxpython.org/Phoenix/docs/html/wx.TopLevelWindow.html#wx.TopLevelWindow.ShowFullScreen contains:

> Showing a window full screen also actually Show s the window if it isn’t shown.

In any case, it must read:

> Showing a window full screen also actually shows the window if it isn’t shown.

But a better wording could be:

> A window is only set in full screen mode if it wasn’t in that state before.

Just an idea, I think “show” should be avoided in that sentence.

BTW, I tried to provide a PR, but I couldn’t find which is the file that contains the error.

The error is also repeated in the development version.

**Comment by swt2c** [comment]
Sorry for the delay, but that's in wxPython Phoenix.  Please open an issue at https://github.com/wxWidgets/Phoenix.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
