### ISSUE TITLE
video full course on how to use

### ISSUE THREAD

**Issue by Moriand** [wxWidgets/wxPython-Classic#30]
Hello, how are you, this message does not fit the theme, but the new ones are starting. Could you please create a complete and detailed course on how to use wxpython ?, I would be delighted if you will be on udemy or any other platform.

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
