### ISSUE TITLE
wx.htm2 load error

### ISSUE THREAD

**Issue by wekay102200** [wxWidgets/wxPython-Classic#32]
File "/home/wukan/work/Noval/noval/tool/HtmlEditor.py", line 21, in <module>
    import wx.html2 as webview
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/html2.py", line 8, in <module>
    import _html2
ImportError: /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_html2.x86_64-linux-gnu.so: undefined symbol: wxEVT_WEBVIEW_NAVIGATED

**Comment by swt2c** [comment]
Sorry for the long delay.  It sounds like your wxWidgets was built without WebView support.  You'll probably have to make sure the webkit development packages are installed and rebuild your wxWidgets.  Or are you using a distribution package, and if so, which one?

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
