### ISSUE TITLE
python 

### ISSUE THREAD

**Issue by ruttydm** [wxWidgets/wxPython-Classic#9]
I copied a small example of wxpython from the internet but i got this error:

`Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import wx
ImportError: No module named 'wx'
`

I have installed the latest version of wxpython and I have already looked on the internet for a solution but nothing works.

I'm on ubuntu 16.10

**Comment by josephernest** [comment]
Can you copy/paste the code @ruttydm so that we can see where's the error? (pastebin.com or a link, etc.)

**Comment by ruttydm** [comment]
The code is just an import line. I think that it is something with the install.

**Comment by mesalu** [comment]
How did you perform the installation?

**Comment by ruttydm** [comment]
I didn't :)

**Comment by RobinD42** [comment]
All issues and PRs for wxPython-Classic (version 3 and earlier) are being closed in preparation for archiving this project. Please shift over to the new [wxPython 4.x](https://wxPython.org) and, if needed, create issues and PRs at the [Phoenix](https://github.com/wxWidgets/Phoenix) GitHub project.
